-- Add missing LeadType enum values
ALTER TYPE "LeadType" ADD VALUE IF NOT EXISTS 'CARPET';
ALTER TYPE "LeadType" ADD VALUE IF NOT EXISTS 'PAINTING';
ALTER TYPE "LeadType" ADD VALUE IF NOT EXISTS 'LANDSCAPING';
ALTER TYPE "LeadType" ADD VALUE IF NOT EXISTS 'MONTHLY_YARD_MAINTENANCE';
ALTER TYPE "LeadType" ADD VALUE IF NOT EXISTS 'ROOFING';
ALTER TYPE "LeadType" ADD VALUE IF NOT EXISTS 'STUCCO';
ALTER TYPE "LeadType" ADD VALUE IF NOT EXISTS 'ADUS';

