-- Add new LeadType enum values
ALTER TYPE "LeadType" ADD VALUE IF NOT EXISTS 'TILE_STONE';
ALTER TYPE "LeadType" ADD VALUE IF NOT EXISTS 'MATERIALS';
ALTER TYPE "LeadType" ADD VALUE IF NOT EXISTS 'CONCRETE';
ALTER TYPE "LeadType" ADD VALUE IF NOT EXISTS 'TURF';

